### ISSUE TITLE
MCF nesting doesn't support multiple chain nesting

### ISSUE THREAD

**Issue by RousseauLambertLP** [geopython/pygeometa#104]
Unlike what's mentioned in the [doc](https://github.com/geopython/pygeometa/blob/master/doc/MCF_Reference.md#nesting-mcfs), pygeometa doesn't seem to support chain nesting. 

It looks like it's only reading one level of MCF nesting.

For example, first I create a MCF for the radar model using a base_mcf for the contact information. Then I'm trying to create a specific radar layer MCF using the radar model MCF and it fails because pygeometa is not able to read the information from the contact file. 

contact.yml:
```
Contact:
    blablabla
```
radar_model.yml:
```
base_mcf: ../contact.yml
Identification:
     titre:
     abstract:
```
radar_layer.yml:
```
base_mcf: ../radar_model.yml
Identification:
     titre: another title
     abstract: another abstract
```

Then I get an error because I have no contact key in my radar_layer.yml:
```
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'contact'
```

If I copy manually the whole contact.yml file into my radar_layer.yml, I don't get an error...

copying @tomkralidis and @alexandreleroux for comments
