### ISSUE TITLE
add capability for generic extent object

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pygeometa#111]
We currently represent spatial properties with the top level `spatial` object.  We have use cases which require the use of multiple spatial extents and projections.

The proposal is to model this after 19115:2003 as follows:

```yaml
identification:
    extent:
        spatial:
            - datatype: vector
              geomtype: point
              crs: 4326
              bbox: -141,42,-52,84
        temporal:
            - start: 2011-11-11
              end: 2012-11-11
```

...and thus remove `spatial` from the root as well as move `temporal_begin` and `temporal_end` from `identification` object.
