### ISSUE TITLE
add scale and distance to spatial section

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#189]
scale and/or distance (resolution) are 2 common fields in many iso19139 oriented metadata profiles, such as https://geonovum.github.io/Metadata-ISO19115/#resolutie. I suggest to include these properties in either the spatial or content section of pygeometa, and return them as part of the iso19139 generation in the relevant fields

identificationInfo[1]/*/spatialResolution/*/equivalentScale/*/denominator and identificationInfo[1]/*/spatialResolution/*/distance

**Comment by pvgenuchten** [comment]
the parameter is already [parsed on OWSLib](https://github.com/geopython/OWSLib/blob/9a878f8c675745c673706c7e76a00e1abf083a25/owslib/iso.py#L514-L529)

Suggestion would be to use these properties in pygeometa (note that usually either scale or resolution is provided):

```
spatial:
  scale: 
    - denominator: 100
    - denominator: 200
  resolution:
     - distance: 100
       uom: m
    - distance 200
      uom: m
```
