### ISSUE TITLE
iso19139 generation fails if distribution.1.url contains '&'

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#190]
an error is thrown:
```
not well-formed (invalid token)
```
If i replace & for `& amp ;` it works fine.

Is this a problem of pygeometa or is the expectation that url's are already encoded within yaml?

```yml
distribution:
  wfs:
    url: https://www.dov.vlaanderen.be/geoserver/wms?SERVICE=WMS&version=1.3.0&request=GetMap
    type: ogc:wfs
    name: WFS
```
