### ISSUE TITLE
concept from thesaurus as uri+label

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#195]
these days catalogues move to capturing concepts (keywords) from thesauri using uri and label. how can I encode uri and label in a single pygeometa keyword property (the label is potentially multilingual)..

current:

```yaml
keywords:
      wmo:
            keywords:
                en: [FOO,BAR]
```

suggested:

```yaml
keywords:
    - uri: example.com/foo 
      name: foo
   - uri:  example.com/bar
     name: 
          en: bar
          fr: bistro
```

for backwards compatibility, would be good to support both cases
