### ISSUE TITLE
Add license restriction to iso19139

### ISSUE THREAD

**Issue by frafra** [geopython/pygeometa#205]
It would be nice to be able to specify the license under `gmd:identificationInfo/gmd:MD_DataIdentification/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useLimitation`.

https://github.com/geopython/pygeometa/blob/c8d4f49146828dd03ca8a1a4c1acdc3d94a187f0/pygeometa/schemas/iso19139/main.j2#L242-L244

**Comment by tomkralidis** [comment]
I'd lean towards something like (in the MCF) the below proposal:

```yaml
identification:
    license:
        name: CC-BY-4.0
        url: https://spdx.org/licenses/CC-BY-4.0.html
```

where the `license` object must define at least one of `name` or `url`.  The above can then be applied in a more generic manner to numerous supported metadata formats, including ISO of course.

@frafra thoughts?
