### ISSUE TITLE
Pygeometa Does Not Automatically Populate Extent Metadata for WCMP2 Record from MCF

### ISSUE THREAD

**Issue by ShaneMill1** [geopython/pygeometa#217]
Given the following MCF:

```
contact:
  pointOfContact:
    address: 5830 University Research Court
    administrativearea: null
    city: College Park
    country: United States
    email: ncep.pmb.dm@noaa.gov
    fax: null
    individualname: null
    organization: National Weather Service
    phone: null
    positionname: null
    postalcode: '20740.0'
    url: https://www.weather.gov/
distribution:
  link-0:
    description: null
    function: null
    name: https://tgftp.nws.noaa.gov/data/raw/ac/
    type: WWW:LINK-1.0-http--link
    url: https://tgftp.nws.noaa.gov/data/raw/ac/
  link-1:
    description: GISC Washington
    function: null
    name: Permanent link
    type: WWW:LINK-1.0-http--link
    url: https://gisc-washington.ncep.noaa.govurn:x-wmo:md:int.wmo.wis::ACAK40PAFC
identification:
  abstract: Hourly Tropical Cyclone product which analyzes tropical cyclone characteristics.
  extents:
    spatial:
    - bbox:
      - -179.14733875388035
      - 51.21526513587736
      - 179.77848000005204
      - 63.54981231678504
    temporal:
    - {}
  keywords:
    keywords-0:
      keywords:
      - climatology
      - meteorology
      - meteorology
      - atmosphericComposition
      type: theme
    keywords-1:
      keywords:
      - GlobalExchange
      type: dataCentre
    keywords-2:
      keywords:
      - TWD
      - SWO
      - TWO
      - TWS
      - SCC
      - PSH
      - DSA
      - CYCLONE
      - Hourly Update
      type: null
  status: null
  title: 'GTS bulletin: ACAK40PAFC for Analyses Cyclone for US Weather forecast Office
    PAFC'
  topiccategory:
  - climatologyMeteorologyAtmosphere
  wmo_topic_hierarchy: noaa.national_weather_service.data.core.weather.surface-based-observations.synop
  wmo_data_policy: core
  rights: Creative Commons Universal License - https://creativecommons.org/publicdomain/zero/1.0/
mcf:
  version: '1.0'
metadata:
  datestamp: '2023-02-21T17:02:04Z'
  hierarchylevel: series
  identifier: urn:x-wmo:md:int.wmo.wis::ACAK40PAFC
```

The following Pygeometa command:

pygeometa metadata generate MCF.yaml --schema=wmo-wcmp2 > MD_urn:x-wmo:md:int.wmo.wis::ACAK40PAFC_20230221170205.json

Generates the following WCMP2 Record:

```
{
    "id": "urn:x-wmo:md:int.wmo.wis::ACAK40PAFC",
    "conformsTo": [
        "http://wis.wmo.int/spec/wcmp/2.0" 
    ],
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -179.14733875388035,
                    51.21526513587736
                ],
                [
                    -179.14733875388035,
                    63.54981231678504
                ],
                [
                    179.77848000005204,
                    63.54981231678504
                ],
                [
                    179.77848000005204,
                    51.21526513587736
                ],
                [
                    -179.14733875388035,
                    51.21526513587736
                ]
            ]
        ]
    },
    "properties": {
        "identifier": "urn:x-wmo:md:int.wmo.wis::ACAK40PAFC",
        "title": "GTS bulletin: ACAK40PAFC for Analyses Cyclone for US Weather forecast Office PAFC",
        "description": "Hourly Tropical Cyclone product which analyzes tropical cyclone characteristics.",
        "themes": [
            {
                "concepts": [
                    "climatology",
                    "meteorology",
                    "meteorology",
                    "atmosphericComposition" 
                ]
            },
            {
                "concepts": [
                    "GlobalExchange" 
                ]
            },
            {
                "concepts": [
                    "TWD",
                    "SWO",
                    "TWO",
                    "TWS",
                    "SCC",
                    "PSH",
                    "DSA",
                    "CYCLONE",
                    "Hourly Update" 
                ]
            }
        ],
        "providers": [
            {
                "name": "National Weather Service",
                "individual": null,
                "positionName": null,
                "contactInfo": {
                    "phone": {
                        "office": null
                    },
                    "email": {
                        "office": null
                    },
                    "address": {
                        "office": {
                            "deliveryPoint": "5830 University Research Court",
                            "city": "College Park",
                            "administrativeArea": null,
                            "postalCode": "20740.0",
                            "country": "United States" 
                        },
                        "onlineResource": {
                            "href": "https://www.weather.gov/" 
                        }
                    },
                    "hoursOfService": null,
                    "contactInstructions": null,
                    "url": {
                        "rel": "canonical",
                        "type": "text/html",
                        "href": "https://www.weather.gov/" 
                    }
                },
                "roles": [
                    {
                        "name": "pointOfContact" 
                    }
                ]
            }
        ],
        "language": null,
        "type": "series",
        "rights": "Creative Commons Universal License - https://creativecommons.org/publicdomain/zero/1.0/",
        "wmo:topicHierarchy": "noaa.national_weather_service.data.core.weather.surface-based-observations.synop",
        "wmo:dataPolicy": "core",
        "created": "2023-03-24T07:17:19Z" 
    },
    "links": [
        {
            "rel": null,
            "href": "https://tgftp.nws.noaa.gov/data/raw/ac/",
            "type": "WWW:LINK-1.0-http--link",
            "title": "https://tgftp.nws.noaa.gov/data/raw/ac/" 
        },
        {
            "rel": null,
            "href": "https://gisc-washington.ncep.noaa.govurn:x-wmo:md:int.wmo.wis::ACAK40PAFC",
            "type": "WWW:LINK-1.0-http--link",
            "title": "Permanent link" 
        }
    ]
}
```

I would expect the following section to be included as well:

```
        "extent": {
            "spatial": {
                "bbox": [
                    [
                        -179.14733875388035,
                        51.21526513587736,
                        179.77848000005204,
                        63.54981231678504
                    ]
                ],
                "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84" 
            },
```

But it appears that the spatial extent section is not automatically generated.
