### ISSUE TITLE
attributes and dimensions alignment vs featuretypes

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#232]
attributes and dimensions share common aspects, such as unit/title/description min/max/avg (if numeric)

suggestion could be to merge both concepts?

Another aspect to  consider in this area are featuretypes, for example the tables in a databases, or sheets in an excel (if the full database is considered a single dataset) 

In stead of registering attributes directly on the content-info element, we would need to model them on a featuretype

```yaml
contentinfo:
   featuretypes:
      - name: books
        identifier: #books
        attributes: 
           - name: title
             type: string
      - name: authors
        identifier: #authors
        attributes:
           - name: name
             type: string
```

Above approach matches with what is suggested in [iso19110](https://www.iso.org/standard/57303.html)
