### ISSUE TITLE
Support for YAML as input format for metadata control file

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/pygeometa#54]
Long term feature request, no rush to implement this on my end. 

It would be useful if pygeometa was to support YAML as input format for metadata in addition to the MCF format.

**Comment by tomkralidis** [comment]
@alexandreleroux questions/comments:

- what's the value proposition around moving to YAML?
- we can certainly do more with YAML as a config format (nesting, better includes, cardinality, etc.)
- should we support both, or just a hard move to YAML (with a migration script for MCF to YAML)?  If we want to support both, then then YAML possibilities are bound to the MCF (i.e. the ini file) limitations
- here's a sample YAML representation of https://github.com/geopython/pygeometa/blob/master/sample.mcf

```yaml
- metadata
    identifier: 3f342f64-9348-11df-ba6a-0014c2c00eab
    language: en
    language_alternate: fr
    charset: utf8
    parentidentifier: someparentid
    hierarchylevel: dataset
    datestamp: 2014-11-11
    dataseturi: http://some/minted/uri
    
- spatial
    datatype: vector
    geomtype: point
    crs: 4326
    bbox: -141,42,-52,84
    
- identification
    language: eng; CAN
    charset: utf8
    title_en: title in English
    title_fr: title in French
    abstract_en: abstract in English
    abstract_fr: abstract in French
    keywords_en: kw1 in English,kw2 in English,kw3 in English
    keywords_fr: kw1 in French,kw2 in French,kw3 in French
    keywords_wmo: FOO,BAR
    keywords_type: theme
    keywords_gc_cst_en: kw1,kw2
    keywords_gc_cst_fr: kw1,kw2
    topiccategory: climatologyMeteorologyAtmosphere
    publication_date: 2000-09-01T00:00:00Z
    fees: None
    accessconstraints: otherRestrictions
    rights_en: Copyright (c) 2010 Her Majesty the Queen in Right of Canada
    rights_fr: Copyright (c) 2010 Her Majesty the Queen in Right of Canada
    url: http://geogratis.ca/geogratis/en/product/search.do?id=08DB5E85-7405-FE3A-2860-CC3663245625
    temporal_begin: 1950-07-31
    temporal_end: now
    status: onGoing
    maintenancefrequency: continual
    
- contact:main
    organization: Environment Canada
    url: http://www.ec.gc.ca/
    individualname: Tom Kralidis
    positionname: Senior Systems Scientist
    phone: +01-123-456-7890
    fax: +01-123-456-7890
    address: 4905 Dufferin Street
    city: Toronto
    administrativearea: Ontario
    postalcode: M3H 5T4
    country: Canada
    email: foo@bar.tld
    hoursofservice: 0700h - 1500h EST
    contactinstructions: email
    
- contact:distribution
    #ref: contact:main
    organization: Environment Canada
    url: http://www.ec.gc.ca/
    individualname: Tom Kralidis
    positionname: Senior Systems Scientist
    phone: +01-123-456-7890
    fax: +01-123-456-7890
    address: 4905 Dufferin Street
    city: Toronto
    administrativearea: Ontario
    postalcode: M3H 5T4
    country: Canada
    email: foo@bar.tld
    hoursofservice: 0700h - 1500h EST
    contactinstructions: email
    
- distribution:waf
    url: http://dd.meteo.gc.ca
    type: WWW:LINK
    name: my waf
    description_en: description in English
    description_fr: description in French
    function: download
    
- distribution:wms
    url: http://dd.meteo.gc.ca
    type: OGC:WMS
    name_en: roads
    name_fr: routes
    description_en: description in English
    description_fr: description in French
    function: download
```

**Comment by alexandreleroux** [comment]
My non-expert understanding:
* yaml's indentation makes it much easier to read than the mcf / ini format
 * this is significant given that's what data stewards in an organisation leveraging pygeometa will use to view and edit metadata records
* like you pointed out already, yaml and its libraries support nesting / includes / cardinality
* I'm fine with supporting only yaml in the future. A tool to migrate from mcf to yaml would indeed be nice for existing pygeometa users, but not necessary?

Have I forgot or am I wrong on anything? Thx

**Comment by alexandreleroux** [comment]
@tomkralidis in your YAML-MCF example, is there a reason both Contact and Distribution are split into distinct yaml elements? Example, why not, for distribution:
``` yaml
- distribution:
    - waf
        url: http://dd.meteo.gc.ca
        type: WWW:LINK
        name: my waf
        description_en: description in English
        description_fr: description in French
        function: download
    -wms
        url: http://dd.meteo.gc.ca
        type: OGC:WMS
        name_en: roads
        name_fr: routes
        description_en: description in English
        description_fr: description in French
        function: download
```
Similar comment for keywords under identification, could they be grouped together? 

``` yaml
- identification
    language: eng; CAN
    charset: utf8
    title_en: title in English
    title_fr: title in French
    abstract_en: abstract in English
    abstract_fr: abstract in French
    keywords:
        keywords_en: kw1 in English,kw2 in English,kw3 in English
        keywords_fr: kw1 in French,kw2 in French,kw3 in French
        keywords_wmo: FOO,BAR
        keywords_type: theme
        keywords_gc_cst_en: kw1,kw2
        keywords_gc_cst_fr: kw1,kw2
```
Does such groupings make sense? Thx! -- Alex

**Comment by tomkralidis** [comment]
Makes sense, and we can apply it to different sections as well.  This will be nice as it will allow clean grouping that wasn't possible before given the ini format.

Updated example:

```yaml
- metadata:
    identifier: 3f342f64-9348-11df-ba6a-0014c2c00eab
    language: en
    language_alternate: fr
    charset: utf8
    parentidentifier: someparentid
    hierarchylevel: dataset
    datestamp: 2014-11-11
    dataseturi: http://some/minted/uri

- spatial:
    datatype: vector
    geomtype: point
    crs: 4326
    bbox: -141,42,-52,84

- identification:
    language: eng; CAN
    charset: utf8
    title_en: title in English
    title_fr: title in French
    abstract_en: abstract in English
    abstract_fr: abstract in French
    keywords:
        default:
            keywords_en: kw1 in English,kw2 in English,kw3 in English
            keywords_fr: kw1 in French,kw2 in French,kw3 in French
        wmo:
            keywords_en: FOO,BAR
            keywords_type: theme
        gc_cst:
            keywords_en: kw1,kw2
            keywords_fr: kw1,kw2
    topiccategory: climatologyMeteorologyAtmosphere
    publication_date: 2000-09-01T00:00:00Z
    fees: None
    accessconstraints: otherRestrictions
    rights_en: Copyright (c) 2010 Her Majesty the Queen in Right of Canada
    rights_fr: Copyright (c) 2010 Her Majesty the Queen in Right of Canada
    url: http://geogratis.ca/geogratis/en/product/search.do?id=08DB5E85-7405-FE3A-2860-CC3663245625
    temporal_begin: 1950-07-31
    temporal_end: now
    status: onGoing
    maintenancefrequency: continual

- contact:
    main:
        organization: Environment Canada
        url: http://www.ec.gc.ca/
        individualname: Tom Kralidis
        positionname: Senior Systems Scientist
        phone: +01-123-456-7890
        fax: +01-123-456-7890
        address: 4905 Dufferin Street
        city: Toronto
        administrativearea: Ontario
        postalcode: M3H 5T4
        country: Canada
        email: foo@bar.tld
        hoursofservice: 0700h - 1500h EST
        contactinstructions: email

    distribution:
        #ref: contact:main
        organization: Environment Canada
        url: http://www.ec.gc.ca/
        individualname: Tom Kralidis
        positionname: Senior Systems Scientist
        phone: +01-123-456-7890
        fax: +01-123-456-7890
        address: 4905 Dufferin Street
        city: Toronto
        administrativearea: Ontario
        postalcode: M3H 5T4
        country: Canada
        email: foo@bar.tld
        hoursofservice: 0700h - 1500h EST
        contactinstructions: email

- distribution:
    waf:
        url: http://dd.meteo.gc.ca
        type: WWW:LINK
        name: my waf
        description_en: description in English
        description_fr: description in French
        function: download

    wms:
        url: http://dd.meteo.gc.ca
        type: OGC:WMS
        name_en: roads
        name_fr: routes
        description_en: description in English
        description_fr: description in French
        function: download
```
